// GENERATED BY HAND, NOT BY A TOOL — but written mechanically, because the
// interesting decisions all live in lib/core/theme/tokens/. This layer only
// exposes them through the theme so call sites never import a token directly.
//
// `lerp` is implemented properly on every field. Returning `this` would compile
// and would silently break AnimatedTheme, and no test that merely reads values
// would notice (spec 001b research R8).

import 'package:flutter/material.dart';

import '../tokens/pc_colors.dart';

/// PcColors — the colors half of the ProductCam theme.
///
/// Read it as `context.pcColors`; see `lib/core/theme/pc_context.dart`.
@immutable
class PcColors extends ThemeExtension<PcColors> {
  const PcColors({
    required this.bgShell,
    required this.bgApp,
    required this.bgSurface,
    required this.bgSurfaceRaised,
    required this.bgSheet,
    required this.bgInput,
    required this.bgTrack,
    required this.bgScrim,
    required this.bgGlass,
    required this.bgLight,
    required this.bgLightSurface,
    required this.textPrimary,
    required this.textSecondary,
    required this.textMuted,
    required this.textInverse,
    required this.textOnAccent,
    required this.textAccent,
    required this.textCaution,
    required this.textDanger,
    required this.accent,
    required this.accentPress,
    required this.accentQuiet,
    required this.accentQuietStrong,
    required this.caution,
    required this.cautionQuiet,
    required this.danger,
    required this.dangerQuiet,
    required this.borderHairline,
    required this.borderSubtle,
    required this.borderStrong,
    required this.borderAccent,
    required this.borderFocus,
    required this.statusQueued,
    required this.statusWorking,
    required this.statusDone,
    required this.statusReview,
    required this.statusError,
    required this.white,
  });

  /// The one instance built from the ported design tokens.
  factory PcColors.fromTokens() => const PcColors(
    bgShell: PcColorTokens.bgShell,
    bgApp: PcColorTokens.bgApp,
    bgSurface: PcColorTokens.bgSurface,
    bgSurfaceRaised: PcColorTokens.bgSurfaceRaised,
    bgSheet: PcColorTokens.bgSheet,
    bgInput: PcColorTokens.bgInput,
    bgTrack: PcColorTokens.bgTrack,
    bgScrim: PcColorTokens.bgScrim,
    bgGlass: PcColorTokens.bgGlass,
    bgLight: PcColorTokens.bgLight,
    bgLightSurface: PcColorTokens.bgLightSurface,
    textPrimary: PcColorTokens.textPrimary,
    textSecondary: PcColorTokens.textSecondary,
    textMuted: PcColorTokens.textMuted,
    textInverse: PcColorTokens.textInverse,
    textOnAccent: PcColorTokens.textOnAccent,
    textAccent: PcColorTokens.textAccent,
    textCaution: PcColorTokens.textCaution,
    textDanger: PcColorTokens.textDanger,
    accent: PcColorTokens.accent,
    accentPress: PcColorTokens.accentPress,
    accentQuiet: PcColorTokens.accentQuiet,
    accentQuietStrong: PcColorTokens.accentQuietStrong,
    caution: PcColorTokens.caution,
    cautionQuiet: PcColorTokens.cautionQuiet,
    danger: PcColorTokens.danger,
    dangerQuiet: PcColorTokens.dangerQuiet,
    borderHairline: PcColorTokens.borderHairline,
    borderSubtle: PcColorTokens.borderSubtle,
    borderStrong: PcColorTokens.borderStrong,
    borderAccent: PcColorTokens.borderAccent,
    borderFocus: PcColorTokens.borderFocus,
    statusQueued: PcColorTokens.statusQueued,
    statusWorking: PcColorTokens.statusWorking,
    statusDone: PcColorTokens.statusDone,
    statusReview: PcColorTokens.statusReview,
    statusError: PcColorTokens.statusError,
    white: PcColorTokens.white,
  );

  final Color bgShell;
  final Color bgApp;
  final Color bgSurface;
  final Color bgSurfaceRaised;
  final Color bgSheet;
  final Color bgInput;
  final Color bgTrack;
  final Color bgScrim;
  final Color bgGlass;
  final Color bgLight;
  final Color bgLightSurface;
  final Color textPrimary;
  final Color textSecondary;
  final Color textMuted;
  final Color textInverse;
  final Color textOnAccent;
  final Color textAccent;
  final Color textCaution;
  final Color textDanger;
  final Color accent;
  final Color accentPress;
  final Color accentQuiet;
  final Color accentQuietStrong;
  final Color caution;
  final Color cautionQuiet;
  final Color danger;
  final Color dangerQuiet;
  final Color borderHairline;
  final Color borderSubtle;
  final Color borderStrong;
  final Color borderAccent;
  final Color borderFocus;
  final Color statusQueued;
  final Color statusWorking;
  final Color statusDone;
  final Color statusReview;
  final Color statusError;
  final Color white;

  // `--accent-hover` is deliberately absent. Hover exists only in the bundle's
  // desktop preview; exposing it here would invite a hover affordance onto a
  // touch product (Constitution XI). It stays in the token file for the audit.
  //
  // The ramps are absent too: semantic aliases are the law (FR-010), and a
  // component reaching past them for `mint200` is how a design system erodes.
  // `white` is the one exception — the shutter ring is literally white and has
  // no semantic name.

  @override
  PcColors copyWith({
    Color? bgShell,
    Color? bgApp,
    Color? bgSurface,
    Color? bgSurfaceRaised,
    Color? bgSheet,
    Color? bgInput,
    Color? bgTrack,
    Color? bgScrim,
    Color? bgGlass,
    Color? bgLight,
    Color? bgLightSurface,
    Color? textPrimary,
    Color? textSecondary,
    Color? textMuted,
    Color? textInverse,
    Color? textOnAccent,
    Color? textAccent,
    Color? textCaution,
    Color? textDanger,
    Color? accent,
    Color? accentPress,
    Color? accentQuiet,
    Color? accentQuietStrong,
    Color? caution,
    Color? cautionQuiet,
    Color? danger,
    Color? dangerQuiet,
    Color? borderHairline,
    Color? borderSubtle,
    Color? borderStrong,
    Color? borderAccent,
    Color? borderFocus,
    Color? statusQueued,
    Color? statusWorking,
    Color? statusDone,
    Color? statusReview,
    Color? statusError,
    Color? white,
  }) {
    return PcColors(
      bgShell: bgShell ?? this.bgShell,
      bgApp: bgApp ?? this.bgApp,
      bgSurface: bgSurface ?? this.bgSurface,
      bgSurfaceRaised: bgSurfaceRaised ?? this.bgSurfaceRaised,
      bgSheet: bgSheet ?? this.bgSheet,
      bgInput: bgInput ?? this.bgInput,
      bgTrack: bgTrack ?? this.bgTrack,
      bgScrim: bgScrim ?? this.bgScrim,
      bgGlass: bgGlass ?? this.bgGlass,
      bgLight: bgLight ?? this.bgLight,
      bgLightSurface: bgLightSurface ?? this.bgLightSurface,
      textPrimary: textPrimary ?? this.textPrimary,
      textSecondary: textSecondary ?? this.textSecondary,
      textMuted: textMuted ?? this.textMuted,
      textInverse: textInverse ?? this.textInverse,
      textOnAccent: textOnAccent ?? this.textOnAccent,
      textAccent: textAccent ?? this.textAccent,
      textCaution: textCaution ?? this.textCaution,
      textDanger: textDanger ?? this.textDanger,
      accent: accent ?? this.accent,
      accentPress: accentPress ?? this.accentPress,
      accentQuiet: accentQuiet ?? this.accentQuiet,
      accentQuietStrong: accentQuietStrong ?? this.accentQuietStrong,
      caution: caution ?? this.caution,
      cautionQuiet: cautionQuiet ?? this.cautionQuiet,
      danger: danger ?? this.danger,
      dangerQuiet: dangerQuiet ?? this.dangerQuiet,
      borderHairline: borderHairline ?? this.borderHairline,
      borderSubtle: borderSubtle ?? this.borderSubtle,
      borderStrong: borderStrong ?? this.borderStrong,
      borderAccent: borderAccent ?? this.borderAccent,
      borderFocus: borderFocus ?? this.borderFocus,
      statusQueued: statusQueued ?? this.statusQueued,
      statusWorking: statusWorking ?? this.statusWorking,
      statusDone: statusDone ?? this.statusDone,
      statusReview: statusReview ?? this.statusReview,
      statusError: statusError ?? this.statusError,
      white: white ?? this.white,
    );
  }

  @override
  PcColors lerp(PcColors? other, double t) {
    if (other == null) return this;
    return PcColors(
      bgShell: Color.lerp(bgShell, other.bgShell, t)!,
      bgApp: Color.lerp(bgApp, other.bgApp, t)!,
      bgSurface: Color.lerp(bgSurface, other.bgSurface, t)!,
      bgSurfaceRaised: Color.lerp(bgSurfaceRaised, other.bgSurfaceRaised, t)!,
      bgSheet: Color.lerp(bgSheet, other.bgSheet, t)!,
      bgInput: Color.lerp(bgInput, other.bgInput, t)!,
      bgTrack: Color.lerp(bgTrack, other.bgTrack, t)!,
      bgScrim: Color.lerp(bgScrim, other.bgScrim, t)!,
      bgGlass: Color.lerp(bgGlass, other.bgGlass, t)!,
      bgLight: Color.lerp(bgLight, other.bgLight, t)!,
      bgLightSurface: Color.lerp(bgLightSurface, other.bgLightSurface, t)!,
      textPrimary: Color.lerp(textPrimary, other.textPrimary, t)!,
      textSecondary: Color.lerp(textSecondary, other.textSecondary, t)!,
      textMuted: Color.lerp(textMuted, other.textMuted, t)!,
      textInverse: Color.lerp(textInverse, other.textInverse, t)!,
      textOnAccent: Color.lerp(textOnAccent, other.textOnAccent, t)!,
      textAccent: Color.lerp(textAccent, other.textAccent, t)!,
      textCaution: Color.lerp(textCaution, other.textCaution, t)!,
      textDanger: Color.lerp(textDanger, other.textDanger, t)!,
      accent: Color.lerp(accent, other.accent, t)!,
      accentPress: Color.lerp(accentPress, other.accentPress, t)!,
      accentQuiet: Color.lerp(accentQuiet, other.accentQuiet, t)!,
      accentQuietStrong: Color.lerp(
        accentQuietStrong,
        other.accentQuietStrong,
        t,
      )!,
      caution: Color.lerp(caution, other.caution, t)!,
      cautionQuiet: Color.lerp(cautionQuiet, other.cautionQuiet, t)!,
      danger: Color.lerp(danger, other.danger, t)!,
      dangerQuiet: Color.lerp(dangerQuiet, other.dangerQuiet, t)!,
      borderHairline: Color.lerp(borderHairline, other.borderHairline, t)!,
      borderSubtle: Color.lerp(borderSubtle, other.borderSubtle, t)!,
      borderStrong: Color.lerp(borderStrong, other.borderStrong, t)!,
      borderAccent: Color.lerp(borderAccent, other.borderAccent, t)!,
      borderFocus: Color.lerp(borderFocus, other.borderFocus, t)!,
      statusQueued: Color.lerp(statusQueued, other.statusQueued, t)!,
      statusWorking: Color.lerp(statusWorking, other.statusWorking, t)!,
      statusDone: Color.lerp(statusDone, other.statusDone, t)!,
      statusReview: Color.lerp(statusReview, other.statusReview, t)!,
      statusError: Color.lerp(statusError, other.statusError, t)!,
      white: Color.lerp(white, other.white, t)!,
    );
  }
}
