// GENERATED BY HAND, NOT BY A TOOL — but written mechanically, because the
// interesting decisions all live in lib/core/theme/tokens/. This layer only
// exposes them through the theme so call sites never import a token directly.
//
// `lerp` is implemented properly on every field. Returning `this` would compile
// and would silently break AnimatedTheme, and no test that merely reads values
// would notice (spec 001b research R8).

import 'dart:ui' show lerpDouble;

import 'package:flutter/material.dart';

import '../tokens/pc_motion.dart';

/// PcMotion — the motion half of the ProductCam theme.
///
/// Read it as `context.pcMotion`; see `lib/core/theme/pc_context.dart`.
@immutable
class PcMotion extends ThemeExtension<PcMotion> {
  const PcMotion({
    required this.instant,
    required this.fast,
    required this.base,
    required this.slow,
    required this.trace,
    required this.lock,
    required this.shutter,
    required this.easeSnap,
    required this.easeOut,
    required this.easeInOut,
    required this.easeLinear,
    required this.pressScale,
    required this.pressScaleShutter,
  });

  /// The one instance built from the ported design tokens.
  factory PcMotion.fromTokens() => const PcMotion(
    instant: PcMotionTokens.instant,
    fast: PcMotionTokens.fast,
    base: PcMotionTokens.base,
    slow: PcMotionTokens.slow,
    trace: PcMotionTokens.trace,
    lock: PcMotionTokens.lock,
    shutter: PcMotionTokens.shutter,
    easeSnap: PcMotionTokens.easeSnap,
    easeOut: PcMotionTokens.easeOut,
    easeInOut: PcMotionTokens.easeInOut,
    easeLinear: PcMotionTokens.easeLinear,
    pressScale: PcMotionTokens.pressScale,
    pressScaleShutter: PcMotionTokens.pressScaleShutter,
  );

  final Duration instant;
  final Duration fast;
  final Duration base;
  final Duration slow;
  final Duration trace;
  final Duration lock;
  final Duration shutter;
  final Curve easeSnap;
  final Curve easeOut;
  final Curve easeInOut;
  final Curve easeLinear;
  final double pressScale;
  final double pressScaleShutter;

  // Curves cannot be interpolated meaningfully, so lerp snaps at the midpoint.
  // That is honest: a half-way-between cubic is not a thing, and pretending
  // otherwise would produce motion nobody designed.
  //
  // The three `transition` shorthands are not fields — they are (duration,
  // curve) pairs already reachable through the members above. See the token
  // file for the decomposition.
  (Duration, Curve) get tPress => (instant, easeSnap);
  (Duration, Curve) get tColor => (fast, easeOut);
  (Duration, Curve) get tSheet => (base, easeOut);

  @override
  PcMotion copyWith({
    Duration? instant,
    Duration? fast,
    Duration? base,
    Duration? slow,
    Duration? trace,
    Duration? lock,
    Duration? shutter,
    Curve? easeSnap,
    Curve? easeOut,
    Curve? easeInOut,
    Curve? easeLinear,
    double? pressScale,
    double? pressScaleShutter,
  }) {
    return PcMotion(
      instant: instant ?? this.instant,
      fast: fast ?? this.fast,
      base: base ?? this.base,
      slow: slow ?? this.slow,
      trace: trace ?? this.trace,
      lock: lock ?? this.lock,
      shutter: shutter ?? this.shutter,
      easeSnap: easeSnap ?? this.easeSnap,
      easeOut: easeOut ?? this.easeOut,
      easeInOut: easeInOut ?? this.easeInOut,
      easeLinear: easeLinear ?? this.easeLinear,
      pressScale: pressScale ?? this.pressScale,
      pressScaleShutter: pressScaleShutter ?? this.pressScaleShutter,
    );
  }

  @override
  PcMotion lerp(PcMotion? other, double t) {
    if (other == null) return this;
    return PcMotion(
      instant: Duration(
        microseconds: lerpDouble(
          instant.inMicroseconds,
          other.instant.inMicroseconds,
          t,
        )!.round(),
      ),
      fast: Duration(
        microseconds: lerpDouble(
          fast.inMicroseconds,
          other.fast.inMicroseconds,
          t,
        )!.round(),
      ),
      base: Duration(
        microseconds: lerpDouble(
          base.inMicroseconds,
          other.base.inMicroseconds,
          t,
        )!.round(),
      ),
      slow: Duration(
        microseconds: lerpDouble(
          slow.inMicroseconds,
          other.slow.inMicroseconds,
          t,
        )!.round(),
      ),
      trace: Duration(
        microseconds: lerpDouble(
          trace.inMicroseconds,
          other.trace.inMicroseconds,
          t,
        )!.round(),
      ),
      lock: Duration(
        microseconds: lerpDouble(
          lock.inMicroseconds,
          other.lock.inMicroseconds,
          t,
        )!.round(),
      ),
      shutter: Duration(
        microseconds: lerpDouble(
          shutter.inMicroseconds,
          other.shutter.inMicroseconds,
          t,
        )!.round(),
      ),
      easeSnap: t < 0.5 ? easeSnap : other.easeSnap,
      easeOut: t < 0.5 ? easeOut : other.easeOut,
      easeInOut: t < 0.5 ? easeInOut : other.easeInOut,
      easeLinear: t < 0.5 ? easeLinear : other.easeLinear,
      pressScale: lerpDouble(pressScale, other.pressScale, t)!,
      pressScaleShutter: lerpDouble(
        pressScaleShutter,
        other.pressScaleShutter,
        t,
      )!,
    );
  }
}
