// GENERATED BY HAND, NOT BY A TOOL — but written mechanically, because the
// interesting decisions all live in lib/core/theme/tokens/. This layer only
// exposes them through the theme so call sites never import a token directly.
//
// `lerp` is implemented properly on every field. Returning `this` would compile
// and would silently break AnimatedTheme, and no test that merely reads values
// would notice (spec 001b research R8).

import 'package:flutter/material.dart';

import '../tokens/pc_radius.dart';

/// PcRadius — the radius half of the ProductCam theme.
///
/// Read it as `context.pcRadius`; see `lib/core/theme/pc_context.dart`.
@immutable
class PcRadius extends ThemeExtension<PcRadius> {
  const PcRadius({
    required this.xs,
    required this.sm,
    required this.md,
    required this.lg,
    required this.xl,
    required this.thumb,
    required this.frame,
    required this.sheetTop,
  });

  /// The one instance built from the ported design tokens.
  factory PcRadius.fromTokens() => const PcRadius(
    xs: PcRadiusTokens.xsAll,
    sm: PcRadiusTokens.smAll,
    md: PcRadiusTokens.mdAll,
    lg: PcRadiusTokens.lgAll,
    xl: PcRadiusTokens.xlAll,
    thumb: PcRadiusTokens.thumbAll,
    frame: PcRadiusTokens.frameAll,
    sheetTop: PcRadiusTokens.sheetTop,
  );

  final BorderRadius xs;
  final BorderRadius sm;
  final BorderRadius md;
  final BorderRadius lg;
  final BorderRadius xl;
  final BorderRadius thumb;
  final BorderRadius frame;
  final BorderRadius sheetTop;

  /// `--r-pill` is a shape rather than a radius — see the token file.
  StadiumBorder get pill => PcRadiusTokens.pill;

  @override
  PcRadius copyWith({
    BorderRadius? xs,
    BorderRadius? sm,
    BorderRadius? md,
    BorderRadius? lg,
    BorderRadius? xl,
    BorderRadius? thumb,
    BorderRadius? frame,
    BorderRadius? sheetTop,
  }) {
    return PcRadius(
      xs: xs ?? this.xs,
      sm: sm ?? this.sm,
      md: md ?? this.md,
      lg: lg ?? this.lg,
      xl: xl ?? this.xl,
      thumb: thumb ?? this.thumb,
      frame: frame ?? this.frame,
      sheetTop: sheetTop ?? this.sheetTop,
    );
  }

  @override
  PcRadius lerp(PcRadius? other, double t) {
    if (other == null) return this;
    return PcRadius(
      xs: BorderRadius.lerp(xs, other.xs, t)!,
      sm: BorderRadius.lerp(sm, other.sm, t)!,
      md: BorderRadius.lerp(md, other.md, t)!,
      lg: BorderRadius.lerp(lg, other.lg, t)!,
      xl: BorderRadius.lerp(xl, other.xl, t)!,
      thumb: BorderRadius.lerp(thumb, other.thumb, t)!,
      frame: BorderRadius.lerp(frame, other.frame, t)!,
      sheetTop: BorderRadius.lerp(sheetTop, other.sheetTop, t)!,
    );
  }
}
