// GENERATED BY HAND, NOT BY A TOOL — but written mechanically, because the
// interesting decisions all live in lib/core/theme/tokens/. This layer only
// exposes them through the theme so call sites never import a token directly.
//
// `lerp` is implemented properly on every field. Returning `this` would compile
// and would silently break AnimatedTheme, and no test that merely reads values
// would notice (spec 001b research R8).

import 'dart:ui' show lerpDouble;

import 'package:flutter/material.dart';

import '../tokens/pc_spacing.dart';

/// PcSpacing — the spacing half of the ProductCam theme.
///
/// Read it as `context.pcSpacing`; see `lib/core/theme/pc_context.dart`.
@immutable
class PcSpacing extends ThemeExtension<PcSpacing> {
  const PcSpacing({
    required this.sp1,
    required this.sp2,
    required this.sp3,
    required this.sp4,
    required this.sp5,
    required this.sp6,
    required this.sp7,
    required this.sp8,
    required this.sp9,
    required this.sp10,
    required this.sp11,
    required this.sp12,
    required this.gutter,
    required this.gutterWide,
    required this.sheetPad,
    required this.touchMin,
    required this.touchComfortable,
    required this.touchShutter,
    required this.touchShutterHit,
    required this.shutterExclusion,
    required this.thumbBand,
    required this.barHeight,
    required this.tabbarHeight,
    required this.gridGap,
    required this.strokeHairline,
    required this.strokeMedium,
    required this.strokeIcon,
    required this.maxTextScaleFactor,
    required this.iconBadge,
    required this.iconInline,
    required this.iconChrome,
    required this.iconLarge,
  });

  /// The one instance built from the ported design tokens.
  factory PcSpacing.fromTokens() => const PcSpacing(
    sp1: PcSpacingTokens.sp1,
    sp2: PcSpacingTokens.sp2,
    sp3: PcSpacingTokens.sp3,
    sp4: PcSpacingTokens.sp4,
    sp5: PcSpacingTokens.sp5,
    sp6: PcSpacingTokens.sp6,
    sp7: PcSpacingTokens.sp7,
    sp8: PcSpacingTokens.sp8,
    sp9: PcSpacingTokens.sp9,
    sp10: PcSpacingTokens.sp10,
    sp11: PcSpacingTokens.sp11,
    sp12: PcSpacingTokens.sp12,
    gutter: PcSpacingTokens.gutter,
    gutterWide: PcSpacingTokens.gutterWide,
    sheetPad: PcSpacingTokens.sheetPad,
    touchMin: PcSpacingTokens.touchMin,
    touchComfortable: PcSpacingTokens.touchComfortable,
    touchShutter: PcSpacingTokens.touchShutter,
    touchShutterHit: PcSpacingTokens.touchShutterHit,
    shutterExclusion: PcSpacingTokens.shutterExclusion,
    thumbBand: PcSpacingTokens.thumbBand,
    barHeight: PcSpacingTokens.barHeight,
    tabbarHeight: PcSpacingTokens.tabbarHeight,
    gridGap: PcSpacingTokens.gridGap,
    strokeHairline: PcSpacingTokens.strokeHairline,
    strokeMedium: PcSpacingTokens.strokeMedium,
    strokeIcon: PcSpacingTokens.strokeIcon,
    maxTextScaleFactor: PcSpacingTokens.maxTextScaleFactor,
    iconBadge: PcSpacingTokens.iconBadge,
    iconInline: PcSpacingTokens.iconInline,
    iconChrome: PcSpacingTokens.iconChrome,
    iconLarge: PcSpacingTokens.iconLarge,
  );

  final double sp1;
  final double sp2;
  final double sp3;
  final double sp4;
  final double sp5;
  final double sp6;
  final double sp7;
  final double sp8;
  final double sp9;
  final double sp10;
  final double sp11;
  final double sp12;
  final double gutter;
  final double gutterWide;
  final double sheetPad;
  final double touchMin;
  final double touchComfortable;
  final double touchShutter;
  final double touchShutterHit;
  final double shutterExclusion;
  final double thumbBand;
  final double barHeight;
  final double tabbarHeight;
  final double gridGap;
  final double strokeHairline;
  final double strokeMedium;
  final double strokeIcon;
  final double maxTextScaleFactor;
  final double iconBadge;
  final double iconInline;
  final double iconChrome;
  final double iconLarge;

  // `--safe-top` / `--safe-bottom` are NOT exposed. They are prototype
  // constants the bundle needed because a browser cannot ask a phone about its
  // notch; real insets come from MediaQuery.viewPaddingOf. Exposing them here
  // would be handing out a footgun (token-catalogue §4).

  @override
  PcSpacing copyWith({
    double? sp1,
    double? sp2,
    double? sp3,
    double? sp4,
    double? sp5,
    double? sp6,
    double? sp7,
    double? sp8,
    double? sp9,
    double? sp10,
    double? sp11,
    double? sp12,
    double? gutter,
    double? gutterWide,
    double? sheetPad,
    double? touchMin,
    double? touchComfortable,
    double? touchShutter,
    double? touchShutterHit,
    double? shutterExclusion,
    double? thumbBand,
    double? barHeight,
    double? tabbarHeight,
    double? gridGap,
    double? strokeHairline,
    double? strokeMedium,
    double? strokeIcon,
    double? maxTextScaleFactor,
    double? iconBadge,
    double? iconInline,
    double? iconChrome,
    double? iconLarge,
  }) {
    return PcSpacing(
      sp1: sp1 ?? this.sp1,
      sp2: sp2 ?? this.sp2,
      sp3: sp3 ?? this.sp3,
      sp4: sp4 ?? this.sp4,
      sp5: sp5 ?? this.sp5,
      sp6: sp6 ?? this.sp6,
      sp7: sp7 ?? this.sp7,
      sp8: sp8 ?? this.sp8,
      sp9: sp9 ?? this.sp9,
      sp10: sp10 ?? this.sp10,
      sp11: sp11 ?? this.sp11,
      sp12: sp12 ?? this.sp12,
      gutter: gutter ?? this.gutter,
      gutterWide: gutterWide ?? this.gutterWide,
      sheetPad: sheetPad ?? this.sheetPad,
      touchMin: touchMin ?? this.touchMin,
      touchComfortable: touchComfortable ?? this.touchComfortable,
      touchShutter: touchShutter ?? this.touchShutter,
      touchShutterHit: touchShutterHit ?? this.touchShutterHit,
      shutterExclusion: shutterExclusion ?? this.shutterExclusion,
      thumbBand: thumbBand ?? this.thumbBand,
      barHeight: barHeight ?? this.barHeight,
      tabbarHeight: tabbarHeight ?? this.tabbarHeight,
      gridGap: gridGap ?? this.gridGap,
      strokeHairline: strokeHairline ?? this.strokeHairline,
      strokeMedium: strokeMedium ?? this.strokeMedium,
      strokeIcon: strokeIcon ?? this.strokeIcon,
      maxTextScaleFactor: maxTextScaleFactor ?? this.maxTextScaleFactor,
      iconBadge: iconBadge ?? this.iconBadge,
      iconInline: iconInline ?? this.iconInline,
      iconChrome: iconChrome ?? this.iconChrome,
      iconLarge: iconLarge ?? this.iconLarge,
    );
  }

  @override
  PcSpacing lerp(PcSpacing? other, double t) {
    if (other == null) return this;
    return PcSpacing(
      sp1: lerpDouble(sp1, other.sp1, t)!,
      sp2: lerpDouble(sp2, other.sp2, t)!,
      sp3: lerpDouble(sp3, other.sp3, t)!,
      sp4: lerpDouble(sp4, other.sp4, t)!,
      sp5: lerpDouble(sp5, other.sp5, t)!,
      sp6: lerpDouble(sp6, other.sp6, t)!,
      sp7: lerpDouble(sp7, other.sp7, t)!,
      sp8: lerpDouble(sp8, other.sp8, t)!,
      sp9: lerpDouble(sp9, other.sp9, t)!,
      sp10: lerpDouble(sp10, other.sp10, t)!,
      sp11: lerpDouble(sp11, other.sp11, t)!,
      sp12: lerpDouble(sp12, other.sp12, t)!,
      gutter: lerpDouble(gutter, other.gutter, t)!,
      gutterWide: lerpDouble(gutterWide, other.gutterWide, t)!,
      sheetPad: lerpDouble(sheetPad, other.sheetPad, t)!,
      touchMin: lerpDouble(touchMin, other.touchMin, t)!,
      touchComfortable: lerpDouble(
        touchComfortable,
        other.touchComfortable,
        t,
      )!,
      touchShutter: lerpDouble(touchShutter, other.touchShutter, t)!,
      touchShutterHit: lerpDouble(touchShutterHit, other.touchShutterHit, t)!,
      shutterExclusion: lerpDouble(
        shutterExclusion,
        other.shutterExclusion,
        t,
      )!,
      thumbBand: lerpDouble(thumbBand, other.thumbBand, t)!,
      barHeight: lerpDouble(barHeight, other.barHeight, t)!,
      tabbarHeight: lerpDouble(tabbarHeight, other.tabbarHeight, t)!,
      gridGap: lerpDouble(gridGap, other.gridGap, t)!,
      strokeHairline: lerpDouble(strokeHairline, other.strokeHairline, t)!,
      strokeMedium: lerpDouble(strokeMedium, other.strokeMedium, t)!,
      strokeIcon: lerpDouble(strokeIcon, other.strokeIcon, t)!,
      maxTextScaleFactor: lerpDouble(
        maxTextScaleFactor,
        other.maxTextScaleFactor,
        t,
      )!,
      iconBadge: lerpDouble(iconBadge, other.iconBadge, t)!,
      iconInline: lerpDouble(iconInline, other.iconInline, t)!,
      iconChrome: lerpDouble(iconChrome, other.iconChrome, t)!,
      iconLarge: lerpDouble(iconLarge, other.iconLarge, t)!,
    );
  }
}
